ideacollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # in this case '' represents the root route
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('ideas/', views.ideas_index, name='index'),
    path('ideas/<int:idea_id>/', views.ideas_detail, name='detail'),
    path('ideas/create/', views.IdeaCreate.as_view(), name='idea_create'),
    path('ideas/<int:pk>/update/', views.IdeaUpdate.as_view(), name='ideas_update'),
    path('ideas/<int:pk>/delete/', views.IdeaDelete.as_view(), name='ideas_delete'),
    path('ideas/<int:idea_id>/add_progressupdate/', views.add_progressupdate, name='add_progressupdate'),
    path('ideas/<int:idea_id>/assoc_tag/<int:tag_id>/', views.assoc_tag, name='assoc_tag'),
    path('tags/', views.TagsList.as_view(), name='tags_index'),
    path('toys/<int:pk>/', views.TagsDetail.as_view(), name='tags_detail'),
    path('tags/create/', views.TagsCreate.as_view(), name='tags_create'),
    path('tags/<int:pk>/update/', views.TagsUpdate.as_view(), name='tags_update'),
    path('tags/<int:pk>/delete/', views.TagsDelete.as_view(), name='tags_delete'),
]

main_app/models.py
from statistics import mode
from unicodedata import category
from django.db import models
from django.urls import reverse

STATUS = {
    ('P','Planning Stage'),
    ('I','InProgress'),
    ('N','Not Started'),
    ('C','Completed'),
}


class Tags(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tags_detail', kwargs={'pk': self.id})    

# Create your models here.
class Idea(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    tags = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    
    taggs = models.ManyToManyField(Tags)

    def  __str__(self):
        return self.name

    # This function gets the detail route with the current Ideas id.
    def get_absolute_url(self):
        return reverse('detail', kwargs={'idea_id': self.id})

class ProgressUpdate(models.Model):
    date = models.DateTimeField('Update on:')
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)

    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.date} - {self.name}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import ProgressUpdate

class ProgressUpdateForm(ModelForm):
  class Meta:
    model = ProgressUpdate
    fields = ['date', 'name', 'description']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Idea, Tags
from .forms import ProgressUpdateForm

# Create your views here.
from django.http import HttpResponse

# Defind the home view


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def ideas_index(request):
    ideas = Idea.objects.all()
    return render(request, 'ideas/index.html', {'ideas': ideas})


def ideas_detail(request, idea_id):
    idea = Idea.objects.get(id=idea_id)
    id_list = idea.taggs.all().values_list('id')
    tags_idea_doesnt_have = Tags.objects.exclude(id__in=id_list)
    progressupdate_form = ProgressUpdateForm()
    return render(request, 'ideas/detail.html', {
        'idea': idea,
        'progressupdate_form': progressupdate_form,
        'tags': tags_idea_doesnt_have,
    })


class IdeaCreate(CreateView):
    model = Idea
    fields = ['name', 'category', 'description', 'status']


class IdeaUpdate(UpdateView):
    model = Idea
    fields = '__all__'


class IdeaDelete(DeleteView):
    model = Idea
    success_url = '/ideas/'


def add_progressupdate(request, idea_id):
    form = ProgressUpdateForm(request.POST)
    if form.is_valid():
        new_progressupdate = form.save(commit=False)
        new_progressupdate.idea_id = idea_id
        new_progressupdate.save()
    return redirect('detail', idea_id=idea_id)


class TagsList(ListView):
    model = Tags


class TagsDetail(DetailView):
    model = Tags


class TagsCreate(CreateView):
    model = Tags
    fields = '__all__'


class TagsUpdate(UpdateView):
    model = Tags
    fields = ['name']


class TagsDelete(DeleteView):
    model = Tags
    success_url = '/tags/'


def assoc_tag(request, idea_id, tag_id):
    Idea.objects.get(id=idea_id).taggs.add(tag_id)
    return redirect('detail', idea_id=idea_id)


def unassoc_tag(request, idea_id, tag_id):
    Idea.objects.get(id=idea_id).taggs.remove(tag_id)
    return redirect('detail', idea_id=idea_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>A litte about us.</h1>
<hr>
<p>It's a good idea.</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Idea Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="{% url 'home'%}" class="left brand-logo">&nbsp;&nbsp;IdeaCollector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about'%}">About</a></li>
                    <li><a href="{% url 'tags_create' %}">Add a Tag</a></li>
                    <li><a href="{% url 'tags_index' %}">View All Tags</a></li>
                    <li><a href="{% url 'idea_create'%}">Add Idea</a></li>
                    <li><a href="{% url 'index' %}">My Ideas</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserved, &copy; 2022 Idea Collector &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Idea Collector HomePage</h1>
{% endblock %}

main_app/templates/ideas/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Idea Details</h1>

<div class="card">
    <div class="card-content">
        <span class="card-title">{{ idea.name }}</span>
        <p>Category: {{ idea.catagory }}</p>
        <p>Description: {{ idea.description }}</p>
        <p>Tags: {{ idea.tags }}</p>
        <p>Status: {{ idea.status }}</p>
    </div>
    <div class="card-action">
        <a href="{% url 'ideas_update' idea.id %}">Edit</a>
        <a href="{% url 'ideas_delete' idea.id %}">Delete</a>
    </div>
</div>
<div class="col s6">
    <form action="{% url 'add_progressupdate' idea.id %}" method="POST">
        {% csrf_token %}
        {{ progressupdate_form.as_p }}
        <input type="submit" class="btn" value="Update Progress">
    </form>
    <table class="striped">
        <thead>
            <tr>
                <th>Date</th>
                <th>Update</th>
            </tr>
        </thead>
        <tbody>
            {% for update in idea.progressupdate_set.all %}
            <tr>
                <td>{{update.date}}</td>
                <td>{{update.name}}</td>
                <td>{{update.description}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ idea.name }}'s Tags</h3>
        {% if idea.taggs.count %}
        {% for tag in idea.taggs.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    {{ tag.name }}
                </span>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>No Tags :(</h5>
        {% endif %}
    </div>
</div>
<div class="row">
  <div class="col s6">
    <h3>Available Tags</h3>
    {% if tags.count %}
    {% for tag in tags.all %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">
                {{ tag.name }}
            </span>
            <form action="{% url 'assoc_tag' idea.id tag.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
          <div class="card-action">
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Tags :(</h5>
    {% endif %}
  </div>
</div>
<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
</script>
{% endblock %}

main_app/templates/ideas/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Idea List</h1>
{% for idea in ideas %}
<div class="card">
    <a href="{% url 'detail' idea.id%}">
        <div class="card-content">
            <span class="card-title">{{ idea.name }}</span>
            <p>Category: {{ idea.catagory }}</p>
            <p>Description: {{ idea.description }}</p>
            <p>Tags: {{ idea.tags }}</p>
            <p>Status: {{ idea.status }}</p>
        </div>
    </a>
</div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/idea_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Idea</h1>

  <h4>Are you sure you want to delete such a great idea - <span class="teal-text">{{ object.name }}</span>?</h4>
  <h4>Think of the project at it's full potential before you confirm!</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a class="btn" href="{% url 'detail' idea.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/idea_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Idea</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
        <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ form.as_table }}
    </table>
    <input type="submit" value="{% if object %}Update{% else %}Add Idea{%endif%}" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/tags_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Tag</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'tags_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/tags_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Tag Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ tags.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'tags_update' tags.id %}">Edit</a>
        <a href="{% url 'tags_delete' tags.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/tags_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Tag</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/tags_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Tag List</h1>

{% for tag in tags_list %}
  <a href="{% url 'tags_detail' tag.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ tag.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}